### ISSUE TITLE
[Non issue] Obligatory question

### ISSUE THREAD

**Issue by FrozenGalaxy** [zombiecute/ModernKitchen#1]
Obligatory question.. are you planning a Forge 1.20.1 version?

**Comment by zombiecute** [comment]
Yes, the Forge version will be uploaded in the future.

**Comment by zombiecute** [comment]
The development of Forge version requires me to spend a lot of energy and time to learn, but because I don't have enough time, I have decided to stop the development of the forge version now. I am very sorry.
