### ISSUE TITLE
add farmers delight refabricated as an optional dependency

### ISSUE THREAD

**Issue by OrdinaryCloverOC** [zombiecute/ModernKitchen#3]
the currently listed farmers delight mod is deprecated, this is an updated one. https://modrinth.com/mod/farmers-delight-refabricated

**Comment by zombiecute** [comment]
farmers delight refabriced has been an optional dependency since version 0.3. And the current version is 0.4.2.

**Comment by zombiecute** [comment]
![image](https://github.com/zombiecute/ModernKitchen/assets/91102690/607fe474-f4e0-4c00-be65-f19caa49f118)

**Comment by OrdinaryCloverOC** [comment]
ah sorry. i looked on aternos and it was not the same as the modrinth dependencies.

**Comment by zombiecute** [comment]
Oh right.
